### ISSUE TITLE
Invalid ASIN Result

### ISSUE THREAD

**Issue by sebclark** [MarcL/AmazonProductAPI#14]
Thanks for this code - it works well - except  If I add an invalid ASIN I get the following (PHP 5.6.30):

Fatal error: Call to undefined method MarcL\Transformers\SimpleArrayTransformer::AddError() in /xxxxxx/html/vendor/marcl/amazonproductapi/src/Transformers/SimpleArrayTransformer.php on line 24

AmazonAPI looks fine

	private function AddError($error) {
		array_push($this->mErrors, $error);
	}

I am using the $items = $amazonAPI->ItemLookUp($asinIds);
Also seems like the itemlookup is limit to 10 items - Amazon restriction?

**Comment by MarcL** [comment]
Hey @sebclark,

Yes - there's definitely a 10 ASIN limit on the `ItemLookup` endpoint.
I'll add a check for it and have a look at the bug for you.

Cheers,
Marc

**Comment by MarcL** [comment]
Hey @sebclark.

Want to grab v3.0.2 and that bug should now be fixed for you. 👍 

Cheers,
Marc

**Comment by Presenze** [comment]
Hi, I'm really a beginner, I can't get the search box to appear on the screen in the home page of the site in php, can anyone help me?

**Comment by MarcL** [comment]
Hey @Presenze.

I think you need to look at some beginner HTML and PHP to get it working.
Take a look at a simple example like [this one](https://www.sourcecodester.com/tutorials/php/12632/php-simple-search-box.html).

Thanks!

**Comment by Presenze** [comment]
> Hey @Presenze.
> 
> I think you need to look at some beginner HTML and PHP to get it working. Take a look at a simple example like [this one](https://www.sourcecodester.com/tutorials/php/12632/php-simple-search-box.html).
> 
> Thanks!

thanks now to make it work I have to connect the amazon api credentials php file and include it in the html file with include ?
