### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by xberg** [MarcL/AmazonProductAPI#2]
Great work Mark: I use this in my project with great joy and despite my complete newbieness! 
Question: how would you modify the code to retrieve the product description from your locale (ie: FR / DE ...)
thanks
Blaise

**Comment by MarcL** [comment]
Hi Blaise,

Sorry, never saw this issue.

You might have solved this already but you can just change the locale before searching or looking up an item.

See the docs here:

https://github.com/MarcL/AmazonProductAPI#usage

You can use this:

``` php
$amazonAPI->SetLocale( 'fr' );
```

Cheers,
Marc
