### ISSUE TITLE
search by subcategory or node

### ISSUE THREAD

**Issue by Malolillo** [MarcL/AmazonProductAPI#21]
Can I make a search by subcategory like "Electronics/Cell Phones & Accessories" ?

**Comment by MarcL** [comment]
Yes - you can search by subcategories @Malolillo. See the API documentation from Amazon here:

https://docs.aws.amazon.com/AWSECommerceService/latest/DG/localevalues.html

I think you can use the blended searches too:

https://docs.aws.amazon.com/AWSECommerceService/latest/DG/BlendedSearches.html

Shout if it doesn't work with my library and I'll take a look.

Cheers,
Marc
