### ISSUE TITLE
How to use this repo without composer

### ISSUE THREAD

**Issue by rajasajidmanzoor** [MarcL/AmazonProductAPI#23]
Hello
I checked, composer is no longer available on internet and its author is saying that they are closing composer. (see https://composer.io/site/)

Can you please confirm how can i use this without Composer

I have  tried following:

`<?php
require('src/AmazonAPI.php');
require('src/AmazonUrlBuilder.php');

use MarcL\AmazonAPI;
use MarcL\AmazonUrlBuilder;

// Setup a new instance of the AmazonUrlBuilder with your keys
$urlBuilder = new AmazonUrlBuilder(
    $keyId,
    $secretKey,
    $associateId,
    'uk'
);

// Setup a new instance of the AmazonAPI and define the type of response
$amazonAPI = new AmazonAPI($urlBuilder, 'simple');

$items = $amazonAPI->ItemSearch('harry potter', 'Books', 'price');

print_r($items);`

And this code returns following error:

Fatal error: Class 'MarcL\Transformers\DataTransformerFactory' not found in \amazonApi\src\AmazonAPI.php on line 68

**Comment by MarcL** [comment]
Hey @rajasajidmanzoor.

You're looking at the wrong composer. It's here:

[Composer](https://getcomposer.org/)

I don't think it'll be going away anytime soon.

Thanks,
Marc

**Comment by rajasajidmanzoor** [comment]
thanks.
I managed to get composer and trying to use this..
But this code is not working as expected..
 I tried using different values and i am getting empty arrays in result.

**Comment by MarcL** [comment]
Can you post a code example here then please?

**Comment by rajasajidmanzoor** [comment]
Yes Here is the code

`
$itemsAsin = $amazonAPI->ItemLookUp('B0007B7XSE', false);  //I have used true as well to see but no luck
print('>> Look up specific ASIN\n');
print_r($itemsAsin);
`

I also tried by searching a keyword/item. see below code

`$items = $amazonAPI->ItemSearch('harry potter', 'Books');
print('>> Harry Potter in Books, sort by featured');
var_dump($items);`

and it is returning an empty array()

**Comment by MarcL** [comment]
Here's some basic test code that I use with my library installed.
This works for me.

```php
<?php

require('vendor/autoload.php');

use MarcL\AmazonAPI;
use MarcL\AmazonUrlBuilder;

$keyId = 'your-amazon-id';
$secretKey = 'your-amazon-secret-key';
$associateId = 'your-amazon-associate-id';
$locale = 'uk';

$urlBuilder = new AmazonUrlBuilder(
    $keyId,
    $secretKey,
    $associateId,
    $locale
);

$amazonAPI = new AmazonAPI($urlBuilder, 'simple');

$items = $amazonAPI->ItemSearch('harry potter', 'Books', 'price');
print_r($items);

$items = $amazonAPI->ItemLookUp('B0007B7XSE');
print_r($items);

?>
```

Which locale are you using? Have you got valid credentials for your locale?

**Comment by PierreG89** [comment]
Hello, I get exactly the same, empty arrays, @rajasajidmanzoor have you found what is going on? Thanks

**Comment by MarcL** [comment]
Hey @PierreG89. Did you work out the problem?

**Comment by PierreG89** [comment]
Hello. Not yet. I think all is ok but I dont have full access to search api yet. Its weird as my website is on dev so I have less chance to have access but I cant finish it without this access. Its same case as needing a car to go to work but without work cant buy a car. I love Amazon.

**Comment by MarcL** [comment]
@PierreG89 It's been a while since I gained access to the Amazon associate scheme. I have UK access but I think they revoked my US access as I hadn't sold anything! Hope you get it sorted soon.
