### ISSUE TITLE
PAAPI 5.0

### ISSUE THREAD

**Issue by tinohager** [MarcL/AmazonProductAPI#35]
For information on this project

[The old Amazon Product Api is shut down on `31 October 2019`](https://dev.to/skatkov/new-amazon-product-advertising-api-is-here-and-you-need-to-migrate-fast-3545)

Documentation for the new API
- [API Reference](https://webservices.amazon.com/paapi5/documentation/)
- [Product Advertising API Scratchpad](https://webservices.amazon.com/paapi5/documentation/play-around-using-scratchpad.html)

**Comment by MarcL** [comment]
Ah ok. Thanks @tinohager. Let me take a look.
