### ISSUE TITLE
Can't run composer require marcl\amazonproductapi

### ISSUE THREAD

**Issue by thinhhaposoft** [MarcL/AmazonProductAPI#8]
I'm trying to run : **composer require marcl\amazonproductapi** but  can't install your package. Please help me!
Thanks so much.
I'm using laravel 5.4, with PHP 7.0.19.
![screen shot 2017-07-23 at 10 52 06 am](https://user-images.githubusercontent.com/23049644/28496423-0e56dadc-6f95-11e7-99e9-470a5cfed5bb.png)

**Comment by MarcL** [comment]
Hey @thinhhaposoft,

Sorry! This was the first time I'd written a `composer` package so I've messed up.
I'd forgotten to actually publish it in the first place and the README was incorrect.
Install using a forward slash and not a backslash:

```shell
composer require marcl/amazonproductapi
```

I've just tried a test project and it seems to install as expected now.
Is it good for you now?

Thanks,
Marc
